{
 "title": "Organization  Device Tracker",
 "time": { "from": "2021-05-16T18:30:00.000Z", "to": "2021-05-19T18:29:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "organization",
    "label": "Organization",
    "query": "SELECT DISTINCT(org_id) FROM devices.device_info"
   },
   {
    "name": "facility",
    "label": "Facility",
    "query": "SELECT DISTINCT(facility_id) from devices.device_info WHERE org_id IN( $organization )"
   }
  ]
 },
 "panels": [
  { "title": "Metrices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "organization" },
  {
   "title": "Pressure Monitor: $organization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  avg(signal_value) AS \"avg_pressure\", \n  min(signal_value) AS \"min_pressure\", \n  max(signal_value) AS \"max_pressure\"\nFROM devices.pressure_metric_tracker\nWHERE\n  $__timeFilter(created_at) AND org_id IN ($organization)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperature Monitor: $organization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  avg(signal_value) AS \"avg_temp\", \n  min(signal_value) AS \"min_temp\", \n  max(signal_value) AS \"max_temp\", \n  percentile_cont(0.99) WITHIN GROUP (ORDER BY signal_value) as p99_temp\nFROM devices.temperature_metric_tracker\nWHERE\n  $__timeFilter(created_at) AND org_id IN ($organization)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Compromised Signals: $organization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(device_timestamp,$__interval),\n  count(signal_value) AS \"total_compromised_signals\"\nFROM devices.compromised_signals as comp INNER JOIN devices.device_info di ON di.device_id = comp.device_id \nWHERE di.org_id IN ($organization) AND \n  $__timeFilter(device_timestamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Faulty Signals: $organization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(device_timestamp,$__interval),\n  count(signal_value) AS \"total_faulty_signals\"\nFROM devices.faulty_signals as comp INNER JOIN devices.device_info di ON di.device_id = comp.device_id \nWHERE di.org_id IN ($organization) AND \n  $__timeFilter(device_timestamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  { "title": "Metrices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Pressure Monitor: $organization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  avg(signal_value) AS \"avg_pressure\", \n  min(signal_value) AS \"min_pressure\", \n  max(signal_value) AS \"max_pressure\"\nFROM devices.pressure_metric_tracker\nWHERE\n  $__timeFilter(created_at) AND org_id IN ($organization)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperature Monitor: $organization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  avg(signal_value) AS \"avg_temp\", \n  min(signal_value) AS \"min_temp\", \n  max(signal_value) AS \"max_temp\", \n  percentile_cont(0.99) WITHIN GROUP (ORDER BY signal_value) as p99_temp\nFROM devices.temperature_metric_tracker\nWHERE\n  $__timeFilter(created_at) AND org_id IN ($organization)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Compromised Signals: $organization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(device_timestamp,$__interval),\n  count(signal_value) AS \"total_compromised_signals\"\nFROM devices.compromised_signals as comp INNER JOIN devices.device_info di ON di.device_id = comp.device_id \nWHERE di.org_id IN ($organization) AND \n  $__timeFilter(device_timestamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Faulty Signals: $organization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(device_timestamp,$__interval),\n  count(signal_value) AS \"total_faulty_signals\"\nFROM devices.faulty_signals as comp INNER JOIN devices.device_info di ON di.device_id = comp.device_id \nWHERE di.org_id IN ($organization) AND \n  $__timeFilter(device_timestamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  { "title": "Metrices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Pressure Monitor: $organization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  avg(signal_value) AS \"avg_pressure\", \n  min(signal_value) AS \"min_pressure\", \n  max(signal_value) AS \"max_pressure\"\nFROM devices.pressure_metric_tracker\nWHERE\n  $__timeFilter(created_at) AND org_id IN ($organization)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperature Monitor: $organization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  avg(signal_value) AS \"avg_temp\", \n  min(signal_value) AS \"min_temp\", \n  max(signal_value) AS \"max_temp\", \n  percentile_cont(0.99) WITHIN GROUP (ORDER BY signal_value) as p99_temp\nFROM devices.temperature_metric_tracker\nWHERE\n  $__timeFilter(created_at) AND org_id IN ($organization)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Compromised Signals: $organization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(device_timestamp,$__interval),\n  count(signal_value) AS \"total_compromised_signals\"\nFROM devices.compromised_signals as comp INNER JOIN devices.device_info di ON di.device_id = comp.device_id \nWHERE di.org_id IN ($organization) AND \n  $__timeFilter(device_timestamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Faulty Signals: $organization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(device_timestamp,$__interval),\n  count(signal_value) AS \"total_faulty_signals\"\nFROM devices.faulty_signals as comp INNER JOIN devices.device_info di ON di.device_id = comp.device_id \nWHERE di.org_id IN ($organization) AND \n  $__timeFilter(device_timestamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}