{
 "title": "Organization wise Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "organization",
    "label": "Organization",
    "query": "SELECT DISTINCT(org_id) FROM devices.device_info"
   },
   {
    "name": "facility",
    "label": "Facility",
    "query": "SELECT DISTINCT(facility_id) from devices.device_info WHERE org_id IN( $organization )"
   }
  ]
 },
 "panels": [
  { "title": "Device Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "organization" },
  {
   "title": "Total Devices: $organization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(device_id) AS \"device_id\"\nFROM devices.device_info\nWHERE\n  org_id IN ($organization) AND facility_id IN ($facility)\n  \n  \n"
    }
   ]
  },
  {
   "title": "Reporting Devices: $organization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT(main.device_id)) FROM (\n\tselect device_id from devices.compromised_signals WHERE $__timeFilter(created_at)\n\tUNION\n\tselect device_id from devices.pressure_metric_tracker WHERE $__timeFilter(created_at)\n\tUNION\n\tselect device_id from devices.temperature_metric_tracker WHERE $__timeFilter(created_at)\n) as main INNER JOIN devices.device_info as di ON di.device_id = main.device_id WHERE org_id IN ($organization)\n"
    }
   ]
  },
  {
   "title": "Compromised Messages: $organization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select COUNT(1) as signal_count from devices.compromised_signals as comp INNER JOIN devices.device_info di ON di.device_id = comp.device_id\nWHERE $__timeFilter(comp.created_at) AND di.org_id IN ($organization)"
    }
   ]
  },
  {
   "title": "Compromised Devices: $organization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select COUNT(DISTINCT(comp.device_id)) from devices.compromised_signals as comp \nINNER JOIN devices.device_info di ON di.device_id = comp.device_id WHERE $__timeFilter(comp.created_at) AND di.org_id IN ($organization)"
    }
   ]
  },
  {
   "title": "Faulty Messages: $organization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select COUNT(1) as signal_count from devices.faulty_signals as flt INNER JOIN devices.device_info di ON di.device_id = flt.device_id\nWHERE $__timeFilter(flt.created_at) AND di.org_id IN ($organization)\n"
    }
   ]
  },
  {
   "title": "Faulty Devices: $organization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select COUNT(DISTINCT(flt.device_id)) as signal_count from devices.faulty_signals as flt INNER JOIN devices.device_info di ON di.device_id = flt.device_id\nWHERE $__timeFilter(flt.created_at) AND di.org_id IN ($organization)"
    }
   ]
  }
 ]
}