{
 "title": "Main",
 "time": { "from": "2021-05-18T21:29:22.400Z", "to": "2021-05-18T23:40:13.511Z" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Signal Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(signal_count) FROM (\n\tselect COUNT(1) as signal_count from devices.faulty_signals WHERE $__timeFilter(created_at)\n\tUNION\n\tselect COUNT(1) as signal_count from devices.compromised_signals WHERE $__timeFilter(created_at)\n\tUNION\n\tselect COUNT(1) as signal_count from devices.pressure_metric_tracker WHERE $__timeFilter(created_at)\n\tUNION\n\tselect COUNT(1) as signal_count from devices.temperature_metric_tracker WHERE $__timeFilter(created_at)\n) as main"
    }
   ]
  },
  {
   "title": "Reporting Devices Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT(device_id)) FROM (\n\tselect device_id from devices.compromised_signals WHERE $__timeFilter(created_at)\n\tUNION\n\tselect device_id from devices.pressure_metric_tracker WHERE $__timeFilter(created_at)\n\tUNION\n\tselect device_id from devices.temperature_metric_tracker WHERE $__timeFilter(created_at)\n) as main"
    }
   ]
  },
  {
   "title": "Offline Devices Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(device_id) FROM devices.device_info WHERE device_id NOT IN(\nSELECT DISTINCT(device_id) FROM (\n\t\tselect device_id from devices.compromised_signals WHERE $__timeFilter(created_at)\n\t\tUNION\n\t\tselect device_id from devices.pressure_metric_tracker WHERE $__timeFilter(created_at)\n\t\tUNION\n\t\tselect device_id from devices.temperature_metric_tracker WHERE $__timeFilter(created_at)\n\t) as main\n)"
    }
   ]
  },
  {
   "title": "p99 Messages Processing Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT signal_category, created_at as time, percentile_cont(0.99) WITHIN GROUP (ORDER BY lag_in_secs) FROM (\n\tselect 'faulty' as signal_category, created_at, device_timestamp, EXTRACT(EPOCH FROM (created_at - device_timestamp )) as lag_in_secs from devices.faulty_signals\n\tUNION\n\tselect 'compromised' as signal_category, created_at, device_timestamp, EXTRACT(EPOCH FROM (created_at - device_timestamp )) as lag_in_secs from devices.compromised_signals\n\tUNION\n\tselect 'temperature' as signal_category, created_at, device_timestamp, EXTRACT(EPOCH FROM (created_at - device_timestamp )) as lag_in_secs from devices.pressure_metric_tracker\n\tUNION\n\tselect 'pressure' as signal_category, created_at, device_timestamp, EXTRACT(EPOCH FROM (created_at - device_timestamp )) as lag_in_secs from devices.temperature_metric_tracker\n)as un WHERE \n  $__timeFilter(created_at)\n  GROUP BY 1,2 \n  ORDER BY created_at,  signal_category DESC\n"
    }
   ]
  },
  { "title": "Compromised Metrices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Compromised Signal Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select COUNT(1) as signal_count from devices.compromised_signals WHERE $__timeFilter(created_at)\n"
    }
   ]
  },
  {
   "title": "Compromised Devices Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\n\tselect COUNT(DISTINCT(device_id))  from devices.compromised_signals WHERE $__timeFilter(created_at)\n\t"
    }
   ]
  },
  {
   "title": "Compromised Signals",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(device_timestamp,$__interval),\n  count(signal_value) AS \"total_compromised_signals\"\nFROM devices.compromised_signals\nWHERE\n  $__timeFilter(device_timestamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  { "title": "Faulty Metrices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Faulty Signals Reported",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select COUNT(1) as signal_count from devices.faulty_signals WHERE $__timeFilter(created_at)\n"
    }
   ]
  },
  {
   "title": "Faulty Devices Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\n\tselect COUNT(DISTINCT(device_id))  from devices.faulty_signals WHERE $__timeFilter(created_at)\n\t"
    }
   ]
  },
  {
   "title": "Faulty Signals",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(device_timestamp,10s),\n  count(signal_value) AS \"total_faulty_signals\"\nFROM devices.faulty_signals\nWHERE\n  $__timeFilter(device_timestamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}