spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database.zeusiot.internal:5432/iot_devices_db?currentSchema=devices
    username: 'root'
    password: 'root'
    platform: postgresql
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 5
      pool-name: MainHikariPool
      data-source-properties:
        useConfigs: maxPerformance
        rewriteBatchedStatements: true

  kafka:
    bootstrap-servers: broker1.zeusiot.internal:9092
    new-topic-config:
      replica-count: 3
      partition-count: 40
    iot-consumer-settings:
      key-value-consumer-concurrency: 8
      json-consumer-concurrency: 8
      device-cluster-concurrency: 4
      all-signal-concurrency: 8

      consumer-batch-size-sm: 10
      consumer-batch-size-md: 500
      consumer-batch-size-lg: 1000


logging:
  level:
    org:
      springframework:
        web: ERROR
        jdbc:
          core: ERROR
    hat.streaming.devices: INFO

server:
  servlet:
    context-path: /api/rest
  port: 7795

info:
  app:
    name: "Stream Processing App"
    app:
      description: "Stream processing app for IOT signal processing"
      api_env: ${SPRING_PROFILES_ACTIVE}

management:
  server:
    port: 7796

  metrics:
    export:
      prometheus:
        enabled: true

  endpoints:
    web:
      base-path: /inspector
      exposure:
        include: prometheus,health,info,env,metrics
