spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/iot_devices_db?currentSchema=devices
    username: 'ankurpandey'
    password: ''
    platform: postgresql
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: MainHikariPool
      data-source-properties:
        useConfigs: maxPerformance
        rewriteBatchedStatements: true

  kafka:
    bootstrap-servers: localhost:9092
    new-topic-config:
      replica-count: 1
      partition-count: 1
    iot-consumer-settings:
      key-value-consumer-concurrency: 1
      json-consumer-concurrency: 1
      device-cluster-concurrency: 1
      all-signal-concurrency: 1
      consumer-batch-size-sm: 10
      consumer-batch-size-md: 10
      consumer-batch-size-lg: 2000

logging:
  level:
    org:
      springframework:
        web: INFO
        jdbc:
          core: ERROR
    hat.streaming.devices: INFO

server:
  servlet:
    context-path: /api/rest
  port: 7795

info:
  app:
    name: "Stream Processing App"
    app:
      description: "Stream processing app for IOT signal processing"
      api_env: ${SPRING_PROFILES_ACTIVE}

management:
  server:
    port: 7796

  metrics:
    export:
      prometheus:
        enabled: true

  endpoints:
    web:
      base-path: /inspector
      exposure:
        include: prometheus,health,info,env,metrics


opentracing:
  jaeger:
    enabled: true
    log-spans: true
    service-name: ziotApp

    udp-sender:
      host: localhost
      port: 6831

